version: '2'
services:
    beyondinfinityapp-app:
        image: beyondinfinityapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://beyondinfinityapp-mysql:3306/beyondinfinityapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    beyondinfinityapp-mysql:
        extends:
            file: mysql.yml
            service: beyondinfinityapp-mysql
